/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
    // Deletes ALL existing entries
    await knex("herramienta_ia").del();
    await knex("herramienta_ia").insert([
      {
        nombreherramienta: "PalM2",
        propositoia: "General Purpose",
        subpropositoia: "Development - Technical Documentation",
        ecosistema: "Foundation Models",
        tipocontenido: "Text",
        descripcion: `PaLM 2 is Google's upgraded AI language model from PaLM 1, improving in reasoning, coding, and translation. Available in different sizes, it's fine-tuned with specific domain data. Although details on training data are limited, it includes various sources. PaLM 2 integrates into Google Bard and Gmail, and is accessible to developers via APIs for use in various products and services.`,
        licencia: "yes",
        imagen: "logo1",
        linkherramienta: "https://ai.google/discover/palm2/",
      },
      {
        nombreherramienta: "Translation AI",
        propositoia: "General Purpose",
        ecosistema: "Cloud Services",
        costo: "Subscription-based",
        tipocontenido: "Text",
        descripcion: `Google Cloud Translate offers text translation between languages, noted for its accuracy, scalability, and ease of use, suitable for multilingual content translation.`,
        costo: "Subscription Based",
        licencia: "yes",
        imagen: "logo2",
        linkherramienta: "https://cloud.google.com/translate",
      },
      {
        nombreherramienta: "Amazon SageMaker",
        propositoia: "General Purpose",
        subpropositoia: "",
        ecosistema: "Applications",
        tipocontenido: "Code",
        descripcion: `Amazon SageMaker is a fully managed machine learning service that supports model building, training, and deployment. It features Jupyter notebooks, IDEs, scalable training environments, and deployment options. Used in industries like retail and healthcare, SageMaker is user-friendly, scalable, cost-effective, and secure, with flexible pricing and AWS integration.`,
        licencia: "yes",
        imagen: "logo3",
        linkherramienta: "https://aws.amazon.com/sagemaker/",
      },
      {
        nombreherramienta: "Amazon Rekognition",
        propositoia: "General Purpose",
        subpropositoia: "",
        ecosistema: "Applications",
        tipocontenido: "Image",
        descripcion: `Amazon Rekognition is a cloud-based machine learning service that identifies objects, faces, and text in images and videos. It's used across multiple industries for content moderation, security, and analytics, offering ease of use, scalability, and security. The service integrates with other AWS services and is available globally.`,
        licencia: "yes",
        imagen: "logo4",
        linkherramienta: "https://aws.amazon.com/rekognition/",
      },
      {
        nombreherramienta: "Amazon Comprehend",
        propositoia: "General Purpose",
        subpropositoia: "",
        ecosistema: "Applications",
        tipocontenido: "Text",
        descripcion: `Amazon Comprehend is a natural language processing service that uses machine learning to analyze text for entities, key phrases, sentiment, and language. Suitable for various industries, it's easy to use, scalable, and secure. Comprehend integrates with other AWS services and is available globally.`,
        licencia: "yes",
        imagen: "logo5",
        linkherramienta:
          "https://aws.amazon.com/blogs/machine-learning/category/artificial-intelligence/amazon-comprehend/",
      },
      {
        nombreherramienta: "Amazon Kendra",
        propositoia: "General Purpose",
        subpropositoia: "",
        ecosistema: "Applications",
        tipocontenido: "Text",
        descripcion: `Amazon Kendra is a machine learning-powered search service that enables natural language searches across various content sources. It offers automatic indexing, customization, and integrates with other AWS services. Kendra is known for its ease of use, accuracy, scalability, and security, making it effective for industries like finance and healthcare.`,
        licencia: "yes",
        imagen: "logo6",
        linkherramienta:
          "https://aws.amazon.com/blogs/machine-learning/category/artificial-intelligence/amazon-kendra/",
      },
      {
        nombreherramienta: "Amazon Lex",
        propositoia: "General Purpose",
        subpropositoia: "",
        ecosistema: "Applications",
        tipocontenido: "Voice",
        descripcion: `Amazon Lex enables building conversational interfaces with voice and text. It features machine learning to understand and respond to user inputs, supporting speech recognition and natural language understanding. Lex is scalable, customizable, and integrates with AWS, ideal for creating chatbots and virtual assistants.`,
        licencia: "yes",
        imagen: "logo7",
        linkherramienta:
          "https://aws.amazon.com/blogs/machine-learning/category/artificial-intelligence/amazon-lex/",
      },
      {
        nombreherramienta: "Amazon Textract",
        propositoia: "General Purpose",
        subpropositoia: "",
        ecosistema: "Data and Integration Services",
        tipocontenido: "Text",
        descripcion: `Amazon Textract is a machine learning service that extracts text, handwriting, and data from scanned documents. It's used in sectors like finance and healthcare for processing invoices, contracts, and receipts. Textract offers text and data extraction, OCR capabilities, and integrates with AWS services, making it suitable for businesses automating document handling.`,
        licencia: "yes",
        imagen: "logo8",
        linkherramienta:
          "https://aws.amazon.com/blogs/machine-learning/category/artificial-intelligence/amazon-textract/",
      },
      {
        nombreherramienta: "Amazon Bedrock",
        propositoia: "General Purpose",
        subpropositoia: "",
        ecosistema: "Cloud Services",
        costo: "Subscription-based",
        tipocontenido: "Text",
        descripcion: `Amazon Bedrock is a managed service that offers foundation models (FMs) via an API, facilitating the use of large language models for text generation, translation, and content creation. It provides quick, scalable, and secure integration, cost-effective for businesses enhancing or building AI-driven applications.`,
        licencia: "yes",
        imagen: "logo9",
        linkherramienta: "https://aws.amazon.com/bedrock/",
      },
      {
        nombreherramienta: "Azure AI Services",
        propositoia: "General Purpose",
        subpropositoia: "",
        ecosistema: "Cloud Services",
        costo: "Subscription-based",
        tipocontenido: "",
        descripcion: `Azure AI Services offers a suite of cloud-based AI tools for creating chatbots, virtual assistants, image recognition systems, and more. This collection includes Azure Cognitive Services, Machine Learning, Bot Service, Speech Services, and Text Analytics. Known for scalability, reliability, and cost-effectiveness, it's a strong option for cloud-based AI development.`,
        licencia: "yes",
        imagen: "logo10",
        linkherramienta: "https://azure.microsoft.com/en-us/products/ai-services/?activetab=pivot:azureopenaiservicetab",
      },
      {
        nombreherramienta: "Krisp",
        propositoia: "General Purpose",
        subpropositoia: "",
        ecosistema: "Applications",
        tipocontenido: "Voice",
        descripcion: `Krisp is an AI-powered software that enhances voice communication by removing background noise and echoes. It integrates with major platforms, processes audio on-device for privacy, and is available in free and paid versions. More information can be found on Krisp’s website.`,
        licencia: "yes",
        imagen: "logo11",
        linkherramienta: "",
      },
      {
        nombreherramienta: "Quillbot",
        propositoia: "General Purpose",
        subpropositoia: "",
        ecosistema: "Applications",
        tipocontenido: "Text",
        descripcion: `QuillBot AI is an AI-powered tool that enhances writing using features like paraphrasing, grammar checking, summarizing, citation generation, and translation. It serves a broad audience, from students to professionals, and is accessible through a web interface with both free and premium options available.`,
        licencia: "yes",
        imagen: "logo12",
        linkherramienta: "",
      },
      {
        nombreherramienta: "LlamaIndex",
        propositoia: "General Purpose",
        subpropositoia: "",
        ecosistema: "Cloud Services",
        tipocontenido: "Text",
        descripcion: `LlamaIndex is a platform that enhances AI applications by integrating custom data with Large Language Models like GPT-4, supporting data ingestion, structuring, and retrieval to improve contextual awareness and response quality.`,
        licencia: "no",
        imagen: "logo13",
        linkherramienta: "",
      },
      {
        nombreherramienta: "Perplexity.ai",
        propositoia: "General Purpose",
        subpropositoia: "",
        ecosistema: "Applications",
        tipocontenido: "Text",
        descripcion: `Perplexity.ai is an AI-powered tool that enhances information discovery across various topics. It offers features like real-time answers via AI-enhanced glasses, recipe suggestions, and fast, reliable responses using GPT-3 technology. Designed for comprehensive and ad-free searches, it supports developer integration and is accessible through web and mobile platforms.`,
        licencia: "yes",
        imagen: "logo14",
        linkherramienta: "",
      },
      {
        nombreherramienta: "Google Gemini",
        propositoia: "General Purpose",
        subpropositoia: "",
        ecosistema: "Foundation Models",
        tipocontenido: "Image",
        descripcion: `Google Gemini, previously Bard, is an AI language model integrated with Google's services. It assists with tasks like coding and summarizing information, and competes with tools like Microsoft's Co-Pilot. Privacy is emphasized, though data is stored for three years, prompting users to avoid sensitive inputs.`,
        licencia: "yes",
        imagen: "logo15",
        linkherramienta: "",
      },
      {
        nombreherramienta: "Imagen",
        propositoia: "Design",
        subpropositoia: "Design - Wireframing and Prototyping",
        ecosistema: "Cloud Services",
        tipocontenido: "Image",
        descripcion: `Imagen on Vertex AI is a generative AI service that utilizes the LaMDA language model to produce high-quality images from text prompts. It supports a wide range of image types, from realistic to creative, adaptable to various subjects, sizes, and styles, serving as a useful tool for visual content creation.`,
        licencia: "yes",
        imagen: "logo16",
        linkherramienta: "https://imagen.research.google/",
      },
      {
        nombreherramienta: "Chirp", //chris
        propositoia: "Marketing",
        subpropositoia: "People - Employee Engagement",
        ecosistema: "Cloud Services",
        tipocontenido: "Text",
        descripcion: `Chirp is Google's speech-to-text model that transcribes speech in multiple languages accurately. It's accessible through the Speech-to-Text API v2 and is ideal for use in call centers, voice assistants, and transcription services.`,
        licencia: "yes",
        imagen: "logo17",
        linkherramienta: "https://cloud.google.com/speech-to-text/v2/docs/chirp-model",
      },
      {
        nombreherramienta: "Natural Language AI",
        propositoia: "Marketing",
        subpropositoia: "Development - Code Writing",
        ecosistema: "Cloud Services",
        tipocontenido: "Text",
        descripcion: `Google Cloud Natural Language offers APIs for understanding text, identifying entities, and analyzing sentiment, enabling easy development of language-processing applications.`,
        licencia: "yes",
        imagen: "logo18",
        linkherramienta: "https://cloud.google.com/natural-language",
      },
      {
        nombreherramienta: "Speech-To-Text",
        propositoia: "Marketing",
        subpropositoia: "",
        ecosistema: "Cloud Services",
        tipocontenido: "Text",
        descripcion: `Google Cloud Speech-to-Text accurately converts speech from audio and video into text, supporting multiple languages. It's ideal for transcribing meetings and adding video captions, providing scalability and security.`,
        licencia: "yes",
        imagen: "logo19",
        linkherramienta: "https://cloud.google.com/speech-to-text",
      },
      {
        nombreherramienta: "Text-To-Speech", 
        propositoia: "Marketing",
        subpropositoia: "",
        ecosistema: "Cloud Services",
        costo: "Subscription-based",
        tipocontenido: "Voice",
        descripcion: `Google Cloud Text-to-Speech converts text to speech in over 100 languages, offering natural sound for applications like audiobooks, podcasts, and virtual assistants. It's known for its accuracy, scalability, and ease of use.`,
        licencia: "yes",
        imagen: "logo20",
        linkherramienta: "https://cloud.google.com/text-to-speech",
      },
      {
        nombreherramienta: "Azure AI Bot Service",
        propositoia: "Marketing",
        subpropositoia: "Marketing - Customer Insights",
        ecosistema: "Applications",
        costo: "Subscription-based",
        tipocontenido: "Text",
        descripcion: `Azure Bot Service is a cloud-based platform for building and deploying chatbots. It offers tools for creating various types of chatbots, such as customer service, sales, and marketing bots. The service is scalable, reliable, easy to use, and cost-effective, making it a suitable choice for those new to chatbot development.`,
        licencia: "yes",
        imagen: "logo21",
        linkherramienta: "https://azure.microsoft.com/en-us/products/ai-services/ai-bot-service",
      },
      {
        nombreherramienta: "Azure OpenAI Service",
        propositoia: "Marketing",
        subpropositoia: "Development - Code Writing",
        ecosistema: "Cloud Services",
        tipocontenido: "Text",
        descripcion: `Azure OpenAI Service offers cloud access to OpenAI's GPT-3 for creating and managing text-based AI tasks such as chatbots and content generation. It's scalable, secure, and user-friendly, with a REST API, SDKs, and documentation provided.`,
        licencia: "yes",
        imagen: "logo22",
        linkherramienta: "https://azure.microsoft.com/en-us/products/ai-services/openai-service",
      },
      {
        nombreherramienta: "Synesthesia",
        propositoia: "Marketing",
        subpropositoia: "",
        ecosistema: "Applications",
        tipocontenido: "Video",
        descripcion: `Synesthesia is a condition where sensory stimuli trigger additional, involuntary experiences, like seeing colors when hearing sounds. Synthesia, however, is an AI startup that develops software for creating digital avatars and media. While AI can analyze data related to synesthesia, understanding its subjective experiences remains dependent on human expertise.`,
        licencia: "yes",
        imagen: "logo23",
        linkherramienta: "",
      },
      {
        nombreherramienta: "Jenni",
        propositoia: "Marketing",
        subpropositoia: "",
        ecosistema: "Applications",
        tipocontenido: "Text",
        descripcion: `Jenni AI is a paraphrasing tool that helps improve academic and technical writing by enabling users to rephrase text for clarity and originality. It supports academic integrity, prevents plagiarism, and offers a user-friendly platform. Basic features are free, with additional services available for purchase on the website.`,
        licencia: "yes",
        imagen: "logo24",
        linkherramienta: "",
      },
      {
        nombreherramienta: "Octane",
        propositoia: "Marketing",
        subpropositoia: "",
        ecosistema: "Applications",
        tipocontenido: "Text",
        descripcion: `Octane AI is a marketing automation platform designed for e-commerce personalization, particularly on Shopify. It uses quizzes and zero-party data collection to engage customers and tailor marketing strategies, helping store owners enhance customer interactions and boost sales.`,
        licencia: "yes",
        imagen: "logo25",
        linkherramienta: "",
      },
      {
        nombreherramienta: "Quotify AI",
        propositoia: "Marketing",
        subpropositoia: "",
        ecosistema: "Applications",
        tipocontenido: "Text",
        descripcion: `Quotify AI is an AI-powered tool that automatically extracts relevant quotes from text-based PDFs, streamlining the process for researchers, students, and writers. It saves time and effort by efficiently identifying significant quotations in lengthy documents, enhancing productivity in academic and professional settings.`,
        licencia: "yes",
        imagen: "logo26",
        linkherramienta: "",
      },
      {
        nombreherramienta: "Suno",
        propositoia: "Marketing",
        subpropositoia: "",
        ecosistema: "Applications",
        tipocontenido: "Music and Sound",
        descripcion: `Suno is an AI startup that offers an easy-to-use music creation tool. It retains rights to music made by free users, who get a non-commercial license. Suno complies with U.S. laws and can alter or stop its services anytime. Microsoft has included Suno in its Copilot for music creation, ensuring outputs are original yet stylistically inspired by selected artists.`,
        licencia: "yes",
        imagen: "logo27",
        linkherramienta: "",
      },
      {
        nombreherramienta: "MusicGen", //FER
        propositoia: "Marketing",
        subpropositoia: "",
        ecosistema: "Foundation Models",
        tipocontenido: "Music and Sound",
        descripcion: `MusicGen is an AI by Meta that generates music from text prompts, designed for research. It produces short samples with enhanced sound quality, and is accessible via a simple web app. It's not for commercial use.`,
        licencia: "no",
        imagen: "logo28",
        linkherramienta: "",
      },
      {
        nombreherramienta: "Video AI",
        propositoia: "Operations",
        subpropositoia: "General Purpose",
        ecosistema: "Cloud Services",
        costo: "Subscription-based",
        tipocontenido: "Video",
        descripcion: `Google Cloud Video Intelligence analyzes videos to detect objects, faces, text, and transcribe audio. It's used for content moderation, video search, and analytics, offering accuracy, scalability, and ease of use.`,
        licencia: "yes",
        imagen: "logo29",
        linkherramienta: "https://cloud.google.com/video-intelligence",
      },
      {
        nombreherramienta: "Vision AI", // Termina CHRIS
        propositoia: "Operations",
        subpropositoia: "General Purpose",
        ecosistema: "Cloud Services",
        costo: "Subscription-based",
        tipocontenido: "Image",
        descripcion: `Google Cloud Vision analyzes images to detect objects, faces, text, landmarks, and barcodes. It supports content moderation, image search, and analytics, known for its accuracy, scalability, and ease of use.`,
        licencia: "yes",
        imagen: "logo30",
        linkherramienta: "https://cloud.google.com/vision",
      },
      {
        nombreherramienta: "Azure Cognitive Search",
        propositoia: "Operations",
        subpropositoia: "Marketing - Content Generation",
        ecosistema: "Cloud Services",
        costo: "Subscription-based",
        tipocontenido: "Text",
        descripcion: `Azure Cognitive Search is a cloud-based search service enhanced by AI, allowing users to search across documents, images, and videos. It offers custom search experiences, scalability, reliability, ease of use, and cost-effectiveness.`,
        licencia: "yes",
        imagen: "logo31",
        linkherramienta: "https://azure.microsoft.com/en-us/products/ai-services/cognitive-search",
      },
      {
        nombreherramienta: "Quickchat AI",
        propositoia: "Operations",
        subpropositoia: "",
        ecosistema: "Applications",
        tipocontenido: "Text",
        descripcion: `Quickchat AI is an AI tool that enhances business efficiency by automating communications and tasks within platforms like Slack and Microsoft Teams. It supports multiple languages, integrates with CRMs, and offers customizable interactions. Available with a free start option, Quickchat AI simplifies customer support and internal workflows.`,
        licencia: "yes",
        imagen: "logo32",
        linkherramienta: "",
      },
      {
        nombreherramienta: "Dialogflow",
        propositoia: "People",
        subpropositoia: "Operations - Customer Support",
        ecosistema: "Applications",
        costo: "Subscription-based",
        tipocontenido: "Video",
        descripcion: `Amazon Polly is a cloud-based text-to-speech service that converts text into natural speech using deep learning. It supports various languages and voices, suitable for e-learning and accessibility applications. Polly is easy to use, scalable, and cost-effective, and it integrates with other AWS services, available globally for speech-enabled applications.`,
        licencia: "yes",
        imagen: "logo33",
        linkherramienta: "https://cloud.google.com/dialogflow",
      },
      {
        nombreherramienta: "Amazon Polly",
        propositoia: "People",
        subpropositoia: "Operations - Customer Support",
        ecosistema: "Applications",
        tipocontenido: "Video",
        descripcion: `Amazon Polly is a cloud-based text-to-speech service that converts text into natural speech using deep learning. It supports various languages and voices, suitable for e-learning and accessibility applications. Polly is easy to use, scalable, and cost-effective, and it integrates with other AWS services, available globally for speech-enabled applications.`,
        licencia: "yes",
        imagen: "logo34",
        linkherramienta: "https://aws.amazon.com/polly/",
      },
      {
        nombreherramienta: "Quizgecko",
        propositoia: "Education",
        subpropositoia: "",
        ecosistema: "Applications",
        tipocontenido: "Text",
        descripcion: `Quizgecko is an AI-powered tool that converts text inputs into interactive quizzes in various formats, designed to enhance learning and retention. It's user-friendly and applicable across educational and training contexts, with a free version available to help streamline quiz creation.`,
        licencia: "yes",
        imagen: "logo35",
        linkherramienta: "",
      },
      {
        nombreherramienta: "Vertex AI",
        propositoia: "Development",
        subpropositoia: "",
        ecosistema: "Cloud Services",
        costo: "Subscription-based",
        tipocontenido: "Code",
        descripcion: `Vertex AI is a machine learning platform that streamlines model building, deployment, and scaling. It features AutoML for code-free training, automation pipelines, and MLOps for production management.`,
        licencia: "yes",
        imagen: "logo36",
        linkherramienta: "https://cloud.google.com/vertex-ai",
      },
      {
        nombreherramienta: "Codey",
        propositoia: "Development",
        subpropositoia: "Development - Technical Documentation",
        ecosistema: "Cloud Services",
        tipocontenido: "Code",
        descripcion: `The Vertex AI Codey APIs, powered by the PaLM 2 model, enable code generation, completion, and discussion across various programming languages. These APIs are designed to automate tasks, speed up coding, and assist in debugging, although they are still under development.`,
        licencia: "yes",
        imagen: "logo37",
        linkherramienta: "https://cloud.google.com/vertex-ai/docs/generative-ai/code/code-models-overview",
      },
      {
        nombreherramienta: "Vertex AI Workbench",
        propositoia: "Development",
        subpropositoia: "Development - Technical Documentation",
        ecosistema: "Applications",
        tipocontenido: "Code",
        descripcion: `Vertex AI Workbench is a managed JupyterLab environment on Google Cloud, built on Google Kubernetes Engine for scalable and reliable ML model development, training, and deployment. It integrates with Google Cloud services, enhancing efficiency for data scientists and ML engineers across the machine learning lifecycle.`,
        licencia: "yes",
        imagen: "logo36",
        linkherramienta: "https://cloud.google.com/vertex-ai-workbench",
      },
      {
        nombreherramienta: "AutoML",
        propositoia: "Development",
        subpropositoia: "Development - Technical Documentation",
        ecosistema: "Cloud Services",
        tipocontenido: "Text",
        descripcion: `Google Cloud AutoML simplifies building and deploying ML models with automated data preparation, feature engineering, model training, and evaluation. It supports tasks like image and text classification, providing scalability, accuracy, and security, enabling developers to create models more efficiently.`,
        licencia: "yes",
        imagen: "logo39",
        linkherramienta: "https://cloud.google.com/automl",
      },
      {
        nombreherramienta: "Amazon EC2 Trn1",
        propositoia: "Development",
        subpropositoia: "Development - Code Writing",
        ecosistema: "Infraestructure",
        costo: "Subscription-based",
        tipocontenido: "",
        descripcion: `Amazon EC2 Trn1 instances use AWS Trainium accelerators for deep learning, supporting 100B+ parameter models with up to 3.4 petaFLOPS of power and NeuronLink interconnects. They are optimized for training large language and computer vision models, emphasizing high performance, low latency, and cost-effectiveness.`,
        licencia: "yes",
        imagen: "logo40",
        linkherramienta: "https://aws.amazon.com/ec2/instance-types/trn1/",
      },
      {
        nombreherramienta: "Amazon EC2 Inf2",
        propositoia: "Development",
        subpropositoia: "Development - Code Writing",
        ecosistema: "Infraestructure",
        costo: "Subscription-based",
        tipocontenido: "",
        descripcion: `Amazon EC2 Inf2 instances use AWS Inferentia accelerators for efficient AI model inference, offering high performance and cost-effectiveness. They support scalable deployments and integrate with Amazon SageMaker, available in all AWS regions.`,
        licencia: "yes",
        imagen: "logo41",
        linkherramienta: "https://aws.amazon.com/ec2/instance-types/inf2/",
      },
      {
        nombreherramienta: "Amazon CodeWhisperer",
        propositoia: "Development",
        subpropositoia: "",
        ecosistema: "Applications",
        costo: "Free",
        tipocontenido: "Text",
        descripcion: `Amazon CodeWhisperer is a machine learning service that provides code completions and recommendations in several programming languages, enhancing coding efficiency and accuracy. Integrated with major IDEs, it offers 10,000 free suggestions globally, with additional suggestions priced at $0.001 each.`,
        licencia: "yes",
        imagen: "logo42",
        linkherramienta: "https://aws.amazon.com/codewhisperer/",
      },
      {
        nombreherramienta: "Azure AI Document Intelligence",
        propositoia: "Development",
        subpropositoia: "General Purpose",
        ecosistema: "Cloud Services",
        costo: "Subscription-based",
        tipocontenido: "Text",
        descripcion: `Azure AI Document Intelligence uses machine learning to automate the extraction of text, tables, and key phrases from various document formats. It streamlines document processing, improves searchability, and enhances data accuracy. The service is scalable, secure, and easy to use, suitable for businesses optimizing document workflows.`,
        licencia: "yes",
        imagen: "logo43",
        linkherramienta: "https://azure.microsoft.com/en-us/products/ai-services/ai-document-intelligence",
      },
      {
        nombreherramienta: "Azure Machine Learning",
        propositoia: "Development",
        subpropositoia: "Development",
        ecosistema: "Cloud Services",
        costo: "Subscription-based",
        tipocontenido: "Text",
        descripcion: `Azure Machine Learning is a user-friendly cloud platform for building, training, and deploying machine learning models, including features like AutoML and model management. It supports various model types and offers scalability and security, ideal for both beginners and experts.`,
        licencia: "yes",
        imagen: "logo44",
        linkherramienta: "https://azure.microsoft.com/en-us/products/machine-learning/",
      },
      {
        nombreherramienta: "Azure Databricks",
        propositoia: "Development",
        subpropositoia: "",
        ecosistema: "Applications",
        costo: "Subscription-based",
        tipocontenido: "3D",
        descripcion: `Azure Databricks is a cloud-based analytics platform that integrates Apache Spark for a range of tasks from data ingestion to machine learning. It's scalable, reliable, and easy to use, making it a cost-effective choice for unified analytics.`,
        licencia: "yes",
        imagen: "logo45",
        linkherramienta: "https://azure.microsoft.com/en-us/products/databricks/",
      },
      {
        nombreherramienta: "Azure Kinect DK",
        propositoia: "Development",
        subpropositoia: "",
        ecosistema: "Applications",
        tipocontenido: "3D",
        descripcion: `Azure Kinect DK is a developer kit equipped with sensors and cameras for building applications that utilize computer vision and speech technologies. It supports diverse functions like pose estimation and facial recognition. The kit is user-friendly, scalable, and affordable, offering an SDK, samples, and tutorials for development.`,
        licencia: "yes",
        imagen: "logo46",
        linkherramienta: "https://azure.microsoft.com/en-us/products/kinect-dk/",
      },
    ]);
  };