/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/e34YvN9w1qE
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardContent, Card } from "@/components/ui/card"
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"

export function Main() {
  return (
    <>
      <section className="bg-gray-100 py-8 dark:bg-gray-800">
        <div className="container mx-auto px-4 md:px-6">
          <div className="flex items-center justify-between">
            <div className="space-y-1">
              <p className="text-sm text-gray-500 dark:text-gray-400">Account Number</p>
              <p className="text-xl font-semibold">123456789</p>
            </div>
            <div className="space-y-1 text-right">
              <p className="text-sm text-gray-500 dark:text-gray-400">Current Balance</p>
              <p className="text-xl font-semibold">$5,432.00</p>
            </div>
          </div>
        </div>
      </section>
      <section className="py-12 md:py-16 lg:py-20">
        <div className="container mx-auto px-4 md:px-6">
          <h2 className="mb-6 text-2xl font-bold md:text-3xl">Housing Options Near You</h2>
          <Carousel className="h-[300px] md:h-[400px]">
            <CarouselContent>
              <CarouselItem className="md:basis-1/2 lg:basis-1/3">
                <div className="p-2">
                  <Card>
                    <img
                      alt="Housing Option"
                      className="aspect-[5/3] overflow-hidden rounded-t-lg object-cover"
                      height="300"
                      src="/placeholder.svg"
                      width="500"
                    />
                    <CardContent className="space-y-2 p-4">
                      <h3 className="text-lg font-semibold">Luxury Apartment</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">
                        Spacious 2-bedroom apartment with modern amenities.
                      </p>
                    </CardContent>
                  </Card>
                </div>
              </CarouselItem>
              <CarouselItem className="md:basis-1/2 lg:basis-1/3">
                <div className="p-2">
                  <Card>
                    <img
                      alt="Housing Option"
                      className="aspect-[5/3] overflow-hidden rounded-t-lg object-cover"
                      height="300"
                      src="/placeholder.svg"
                      width="500"
                    />
                    <CardContent className="space-y-2 p-4">
                      <h3 className="text-lg font-semibold">Cozy Townhouse</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">
                        Charming 3-bedroom townhouse with a private backyard.
                      </p>
                    </CardContent>
                  </Card>
                </div>
              </CarouselItem>
              <CarouselItem className="md:basis-1/2 lg:basis-1/3">
                <div className="p-2">
                  <Card>
                    <img
                      alt="Housing Option"
                      className="aspect-[5/3] overflow-hidden rounded-t-lg object-cover"
                      height="300"
                      src="/placeholder.svg"
                      width="500"
                    />
                    <CardContent className="space-y-2 p-4">
                      <h3 className="text-lg font-semibold">Modern Loft</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">
                        Stylish 1-bedroom loft with high ceilings and exposed brick.
                      </p>
                    </CardContent>
                  </Card>
                </div>
              </CarouselItem>
            </CarouselContent>
            <CarouselPrevious />
            <CarouselNext />
          </Carousel>
        </div>
      </section>
      <section className="py-12 md:py-16 lg:py-20">
        <div className="container mx-auto px-4 md:px-6">
          <h2 className="mb-6 text-2xl font-bold md:text-3xl">Featured Promotions</h2>
          <Carousel className="h-[300px] md:h-[400px]">
            <CarouselContent>
              <CarouselItem className="md:basis-1/2 lg:basis-1/3">
                <div className="p-2">
                  <Card>
                    <img
                      alt="Promotion"
                      className="aspect-[5/3] overflow-hidden rounded-t-lg object-cover"
                      height="300"
                      src="/placeholder.svg"
                      width="500"
                    />
                    <CardContent className="space-y-2 p-4">
                      <h3 className="text-lg font-semibold">Summer Sale</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">Up to 50% off on selected items.</p>
                    </CardContent>
                  </Card>
                </div>
              </CarouselItem>
              <CarouselItem className="md:basis-1/2 lg:basis-1/3">
                <div className="p-2">
                  <Card>
                    <img
                      alt="Promotion"
                      className="aspect-[5/3] overflow-hidden rounded-t-lg object-cover"
                      height="300"
                      src="/placeholder.svg"
                      width="500"
                    />
                    <CardContent className="space-y-2 p-4">
                      <h3 className="text-lg font-semibold">Free Shipping</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">
                        Get free shipping on all orders over $50.
                      </p>
                    </CardContent>
                  </Card>
                </div>
              </CarouselItem>
              <CarouselItem className="md:basis-1/2 lg:basis-1/3">
                <div className="p-2">
                  <Card>
                    <img
                      alt="Promotion"
                      className="aspect-[5/3] overflow-hidden rounded-t-lg object-cover"
                      height="300"
                      src="/placeholder.svg"
                      width="500"
                    />
                    <CardContent className="space-y-2 p-4">
                      <h3 className="text-lg font-semibold">Buy One, Get One</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">
                        Buy one, get one free on selected products.
                      </p>
                    </CardContent>
                  </Card>
                </div>
              </CarouselItem>
            </CarouselContent>
            <CarouselPrevious />
            <CarouselNext />
          </Carousel>
        </div>
      </section>
      <section className="py-12 md:py-16 lg:py-20">
        <div className="container mx-auto px-4 md:px-6">
          <h2 className="mb-6 text-2xl font-bold md:text-3xl">Nearby Services</h2>
          <Carousel className="h-[200px] md:h-[250px]">
            <CarouselContent>
              <CarouselItem className="md:basis-1/2 lg:basis-1/4">
                <div className="p-2">
                  <Card>
                    <CardContent className="flex flex-col items-center justify-center gap-2 p-4">
                      <MenuIcon className="h-8 w-8" />
                      <h3 className="text-lg font-semibold">Restaurants</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">Discover top-rated dining options.</p>
                    </CardContent>
                  </Card>
                </div>
              </CarouselItem>
              <CarouselItem className="md:basis-1/2 lg:basis-1/4">
                <div className="p-2">
                  <Card>
                    <CardContent className="flex flex-col items-center justify-center gap-2 p-4">
                      <ShoppingBagIcon className="h-8 w-8" />
                      <h3 className="text-lg font-semibold">Shopping</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">Explore local shops and boutiques.</p>
                    </CardContent>
                  </Card>
                </div>
              </CarouselItem>
              <CarouselItem className="md:basis-1/2 lg:basis-1/4">
                <div className="p-2">
                  <Card>
                    <CardContent className="flex flex-col items-center justify-center gap-2 p-4">
                      <CircleParkingIcon className="h-8 w-8" />
                      <h3 className="text-lg font-semibold">Parks</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">Enjoy the great outdoors.</p>
                    </CardContent>
                  </Card>
                </div>
              </CarouselItem>
              <CarouselItem className="md:basis-1/2 lg:basis-1/4">
                <div className="p-2">
                  <Card>
                    <CardContent className="flex flex-col items-center justify-center gap-2 p-4">
                      <DumbbellIcon className="h-8 w-8" />
                      <h3 className="text-lg font-semibold">Gyms</h3>
                      <p className="text-sm text-gray-500 dark:text-gray-400">Stay fit and healthy.</p>
                    </CardContent>
                  </Card>
                </div>
              </CarouselItem>
            </CarouselContent>
            <CarouselPrevious />
            <CarouselNext />
          </Carousel>
        </div>
      </section>
    </>
  )
}

function CircleParkingIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M9 17V7h4a3 3 0 0 1 0 6H9" />
    </svg>
  )
}


function DumbbellIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.4 14.4 9.6 9.6" />
      <path d="M18.657 21.485a2 2 0 1 1-2.829-2.828l-1.767 1.768a2 2 0 1 1-2.829-2.829l6.364-6.364a2 2 0 1 1 2.829 2.829l-1.768 1.767a2 2 0 1 1 2.828 2.829z" />
      <path d="m21.5 21.5-1.4-1.4" />
      <path d="M3.9 3.9 2.5 2.5" />
      <path d="M6.404 12.768a2 2 0 1 1-2.829-2.829l1.768-1.767a2 2 0 1 1-2.828-2.829l2.828-2.828a2 2 0 1 1 2.829 2.828l1.767-1.768a2 2 0 1 1 2.829 2.829z" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function ShoppingBagIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4Z" />
      <path d="M3 6h18" />
      <path d="M16 10a4 4 0 0 1-8 0" />
    </svg>
  )
}
