/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/TOq1fGmm045
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Progress } from "@/components/ui/progress"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"
import { Button } from "@/components/ui/button"

export function MultiStep() {
  return (
    <div className="w-full max-w-3xl mx-auto py-12 md:py-16">
      <div className="flex items-center justify-between mb-8">
        <h1 className="text-3xl font-bold">Multi-Step Form</h1>
        <Progress className="w-full max-w-md" value={33} />
      </div>
      <div className="bg-white dark:bg-gray-900 rounded-lg shadow-lg p-8 md:p-12">
        <form>
          <div className="grid grid-cols-2 gap-6">
            <div className="space-y-4">
              <div>
                <Label htmlFor="age">Age</Label>
                <Input id="age" placeholder="Enter your age" type="number" />
              </div>
              <div>
                <Label htmlFor="name">Name</Label>
                <Input id="name" placeholder="Enter your name" type="text" />
              </div>
            </div>
            <div className="space-y-4">
              <div>
                <Label>Continents</Label>
                <div className="grid grid-cols-2 gap-2">
                  <Checkbox id="north-america" name="continents" value="north-america">
                    North America
                  </Checkbox>
                  <Checkbox id="south-america" name="continents" value="south-america">
                    South America
                  </Checkbox>
                  <Checkbox id="europe" name="continents" value="europe">
                    Europe
                  </Checkbox>
                  <Checkbox id="asia" name="continents" value="asia">
                    Asia
                  </Checkbox>
                  <Checkbox id="africa" name="continents" value="africa">
                    Africa
                  </Checkbox>
                  <Checkbox id="australia" name="continents" value="australia">
                    Australia
                  </Checkbox>
                  <Checkbox id="antarctica" name="continents" value="antarctica">
                    Antarctica
                  </Checkbox>
                </div>
              </div>
              <div>
                <Label>Hobbies</Label>
                <div className="grid grid-cols-2 gap-2">
                  <Checkbox className="text-red-500" id="reading" name="hobbies" value="reading">
                    Reading
                  </Checkbox>
                  <Checkbox className="text-green-500" id="traveling" name="hobbies" value="traveling">
                    Traveling
                  </Checkbox>
                  <Checkbox className="text-yellow-500" id="cooking" name="hobbies" value="cooking">
                    Cooking
                  </Checkbox>
                  <Checkbox className="text-blue-500" id="gardening" name="hobbies" value="gardening">
                    Gardening
                  </Checkbox>
                </div>
              </div>
              <div>
                <Label>Interests</Label>
                <div className="grid grid-cols-2 gap-2">
                  <Checkbox className="text-purple-500" id="technology" name="interests" value="technology">
                    Technology
                  </Checkbox>
                  <Checkbox className="text-pink-500" id="art" name="interests" value="art">
                    Art
                  </Checkbox>
                  <Checkbox className="text-indigo-500" id="music" name="interests" value="music">
                    Music
                  </Checkbox>
                  <Checkbox className="text-orange-500" id="sports" name="interests" value="sports">
                    Sports
                  </Checkbox>
                </div>
              </div>
            </div>
          </div>
          <div className="flex justify-between mt-8">
            <Button variant="outline">Back</Button>
            <Button>Next</Button>
          </div>
        </form>
      </div>
    </div>
  )
}
