/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/B0jY4csQ0po
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardContent, Card } from "@/components/ui/card"
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"

export function Promos() {
  return (
    <Carousel className="w-full max-w-6xl mx-auto">
      <CarouselContent>
        <CarouselItem className="md:basis-1/2 lg:basis-1/3 xl:basis-1/4">
          <div className="p-4">
            <Card className="h-full bg-gradient-to-br from-[#ff6b6b] to-[#ffa500] text-white">
              <img
                alt="Promotion 1"
                className="rounded-t-md object-cover w-full h-48"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <CardContent className="p-4 space-y-2">
                <h3 className="text-lg font-semibold">Summer Sale</h3>
                <div className="flex items-center gap-2">
                  <span className="text-xl font-bold">$29.99</span>
                  <span className="text-sm text-gray-300 line-through">$49.99</span>
                </div>
                <p className="text-sm text-gray-300">New York, NY</p>
              </CardContent>
            </Card>
          </div>
        </CarouselItem>
        <CarouselItem className="md:basis-1/2 lg:basis-1/3 xl:basis-1/4">
          <div className="p-4">
            <Card className="h-full bg-gradient-to-br from-[#9b59b6] to-[#8e44ad] text-white">
              <img
                alt="Promotion 2"
                className="rounded-t-md object-cover w-full h-48"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <CardContent className="p-4 space-y-2">
                <h3 className="text-lg font-semibold">Back to School</h3>
                <div className="flex items-center gap-2">
                  <span className="text-xl font-bold">$19.99</span>
                  <span className="text-sm text-gray-300 line-through">$29.99</span>
                </div>
                <p className="text-sm text-gray-300">Chicago, IL</p>
              </CardContent>
            </Card>
          </div>
        </CarouselItem>
        <CarouselItem className="md:basis-1/2 lg:basis-1/3 xl:basis-1/4">
          <div className="p-4">
            <Card className="h-full bg-gradient-to-br from-[#2980b9] to-[#3498db] text-white">
              <img
                alt="Promotion 3"
                className="rounded-t-md object-cover w-full h-48"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <CardContent className="p-4 space-y-2">
                <h3 className="text-lg font-semibold">Fall Collection</h3>
                <div className="flex items-center gap-2">
                  <span className="text-xl font-bold">$39.99</span>
                  <span className="text-sm text-gray-300 line-through">$59.99</span>
                </div>
                <p className="text-sm text-gray-300">Los Angeles, CA</p>
              </CardContent>
            </Card>
          </div>
        </CarouselItem>
        <CarouselItem className="md:basis-1/2 lg:basis-1/3 xl:basis-1/4">
          <div className="p-4">
            <Card className="h-full bg-gradient-to-br from-[#27ae60] to-[#2ecc71] text-white">
              <img
                alt="Promotion 4"
                className="rounded-t-md object-cover w-full h-48"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <CardContent className="p-4 space-y-2">
                <h3 className="text-lg font-semibold">Winter Essentials</h3>
                <div className="flex items-center gap-2">
                  <span className="text-xl font-bold">$24.99</span>
                  <span className="text-sm text-gray-300 line-through">$39.99</span>
                </div>
                <p className="text-sm text-gray-300">Seattle, WA</p>
              </CardContent>
            </Card>
          </div>
        </CarouselItem>
        <CarouselItem className="md:basis-1/2 lg:basis-1/3 xl:basis-1/4">
          <div className="p-4">
            <Card className="h-full bg-gradient-to-br from-[#e67e22] to-[#f39c12] text-white">
              <img
                alt="Promotion 5"
                className="rounded-t-md object-cover w-full h-48"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "300/200",
                  objectFit: "cover",
                }}
                width="300"
              />
              <CardContent className="p-4 space-y-2">
                <h3 className="text-lg font-semibold">Holiday Deals</h3>
                <div className="flex items-center gap-2">
                  <span className="text-xl font-bold">$34.99</span>
                  <span className="text-sm text-gray-300 line-through">$49.99</span>
                </div>
                <p className="text-sm text-gray-300">Miami, FL</p>
              </CardContent>
            </Card>
          </div>
        </CarouselItem>
      </CarouselContent>
      <CarouselPrevious />
      <CarouselNext />
    </Carousel>
  )
}
